[supervisord]
nodaemon=true
logfile=/var/www/storage/logs/supervisord_%(ENV_PROCESS)s.log
pidfile=/var/www/storage/logs/supervisord_%(ENV_PROCESS)s.pid
loglevel=debug
user=root

[program:php]
directory=/var/www/
command=%(ENV_COMMAND)s
process_name=%(program_name)s_%(process_num)02d
startretries=20
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/supervisord_%(ENV_PROCESS)s_output.log
stderr_logfile=/var/www/storage/logs/supervisord_%(ENV_PROCESS)s_error.log
priority=1
environment=FRANKENPHP_CONFIG="/etc/caddy/Caddyfile",PHP_CLI_SERVER_WORKERS="4"
