name: Deploy To Staging

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'

jobs:
  deploy:
    name: Deploy staging from ${{ github.ref_name }}
    runs-on: mw-staging
    environment:
      name: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Pull latest changes
        run: |
          git fetch
          git checkout ${{ github.ref }}
          git pull origin ${{ github.ref }}

      - name: Create .env file
        run: |
          cat > .env << 'EOL'
          ${{ secrets.ENV_FILE }}
          EOL

      - name: Docker deploy
        run: |
          docker compose down --remove-orphans
          docker compose up -d --build
          sleep 10

          docker compose exec app yarn install --frozen-lockfile
          docker compose exec app yarn build

          docker compose exec app composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          docker compose exec app php artisan optimize

          docker compose exec app php artisan migrate --force
